# The Docker image to run your workspace in. Defaults to gitpod/workspace-full
image: workspace-dotnet:latest
# Command to start on workspace startup (optional)
tasks:
# Ports to expose on workspace startup (optional)
ports:
  - port: 8000
    onOpen: open-preview
